# Generated by Django 3.2.8 on 2022-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20220514_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='today_award',
            field=models.IntegerField(default=0),
        ),
    ]
