# Generated by Django 3.2.8 on 2022-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agree_to_processing_personal_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirm_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirm_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
